### ISSUE TITLE
Simple skeleton app not working

### ISSUE THREAD

**Issue by noorbakerally** [ldp4j/ldp4j#28]
I've started a simple skeleton app using ldp4j but it's not working. I've hosted the app on github here https://github.com/noorbakerally/ldp4j_sampleapp1. I'm using the [eswc tutorial](http://www.ldp4j.org/tutorials/eswc2015/pdfs/eswc-2015-tutorial-4-hands-on.pdf). I'm sure this must be due to some misconfiguration in my codes but i'm unable to identify them. 

The application is correctly starting but not bootstrapping in the target application. 

A simple output from running the app:

```
[INFO] Scanning for projects...
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building ldp4jsampleapp1 1.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- tomcat7-maven-plugin:2.0:run-war-only (default-cli) @ ldp4jsampleapp1 ---
[INFO] Running war on http://localhost:8081/ldp4jsampleapp1
[INFO] Creating Tomcat server configuration at /home/bakerally/Documents/repositories/github/ldp4j_sampleapp1/target/tomcat
[INFO] create webapp with contextPath: /ldp4jsampleapp1
Mar 03, 2017 11:52:14 AM org.apache.coyote.AbstractProtocol init
INFO: Initializing ProtocolHandler ["http-bio-8081"]
Mar 03, 2017 11:52:14 AM org.apache.catalina.core.StandardService startInternal
INFO: Starting service Tomcat
Mar 03, 2017 11:52:14 AM org.apache.catalina.core.StandardEngine startInternal
INFO: Starting Servlet Engine: Apache Tomcat/7.0.30
Mar 03, 2017 11:52:15 AM org.apache.coyote.AbstractProtocol start
INFO: Starting ProtocolHandler ["http-bio-8081"]
```

it is not entering the setup in the application class as part of the setup include logging:

```
public void setup(Environment environment, Bootstrap<Configuration> bootstrap) throws ApplicationSetupException {
        LOGGER.info("Starting Application configuration...");
......
}
```

can I get some hints on how to solve this ? 
thanks
Noor

**Comment by mestebangutierrez** [comment]
If you plan to follow the tutorial as presented at _ESWC 2015_, please follow the instructions in the repository for the [ESWC 2015 tutorial](https://github.com/ldp4j/eswc2015-tutorial/).

However, if you prefer to use the most up-to-date version of the framework (which *should* be backwards compatible with the version used in the tutorial), just update the version of LDP4j to `0.2.1`, instead of using `1.0.0-SNAPSHOT`.

**Comment by noorbakerally** [comment]
I change the version to 0.2.1 in two files:
- pom.xml of frontend-core
- pom.xml of dist

when compiling, getting the following errors:

```
[INFO] Scanning for projects...
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Build Order:
[INFO] 
[INFO] ESWC 2015 Tutorial
[INFO] ESWC 2015 Tutorial :: Frontend
[INFO] ESWC 2015 Tutorial :: Frontend :: Core
[INFO] ESWC 2015 Tutorial :: Frontend :: Distributable
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building ESWC 2015 Tutorial 1.0.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-enforcer-plugin:1.3.1:enforce (enforce-maven-3) @ eswc-2015 ---
[INFO] 
[INFO] --- maven-dependency-plugin:2.5.1:unpack (unpack) @ eswc-2015 ---
[INFO] Configured Artifact: org.ldp4j:ldp4j-config:1.0.0-SNAPSHOT:jar
[INFO] ldp4j-config-1.0.0-SNAPSHOT.jar already unpacked.
[INFO] 
[INFO] --- maven-jgit-buildnumber-plugin:1.2.8:extract-buildnumber (git-buildnumber) @ eswc-2015 ---
[INFO] Git info extracted, revision: 'baafbaa', branch: 'minimalapp', tag: '', commitsCount: '59', buildnumber: 'baafbaa'
[INFO] 
[INFO] --- gmaven-plugin:1.0:execute (buildNumber) @ eswc-2015 ---
Build number: 1.0.0-SNAPSHOT build 59 (minimalapp@baafbaa)
[INFO] 
[INFO] --- jacoco-maven-plugin:0.7.1.201405082137:prepare-agent (default-prepare-agent) @ eswc-2015 ---
[INFO] jacoco.agent.ut.arg set to -javaagent:/home/bakerally/.m2/repository/org/jacoco/org.jacoco.agent/0.7.1.201405082137/org.jacoco.agent-0.7.1.201405082137-runtime.jar=destfile=/home/bakerally/Documents/repositories/github/LDPTest3/target/coverage-reports/jacoco-ut.exec,includes=org.ldp4j.*
[INFO] 
[INFO] --- build-helper-maven-plugin:1.8:timestamp-property (timestamp-property) @ eswc-2015 ---
[WARNING] Using platform locale (en_US actually) to format date/time, i.e. build is platform dependent!
[INFO] 
[INFO] --- license-maven-plugin:2.6:format (update-licenses) @ eswc-2015 ---
[INFO] Updating license headers...
[INFO] Updating license header in: /home/bakerally/Documents/repositories/github/LDPTest3/frontend/dist/pom.xml
[INFO] Updating license header in: /home/bakerally/Documents/repositories/github/LDPTest3/frontend/pom.xml
[INFO] Updating license header in: /home/bakerally/Documents/repositories/github/LDPTest3/frontend/core/pom.xml
[INFO] 
[INFO] --- build-helper-maven-plugin:1.8:add-resource (install-legal-files) @ eswc-2015 ---
[INFO] 
[INFO] --- build-helper-maven-plugin:1.8:add-resource (install-test-legal-files) @ eswc-2015 ---
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building ESWC 2015 Tutorial :: Frontend 1.0.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-enforcer-plugin:1.3.1:enforce (enforce-maven-3) @ eswc-2015-frontend ---
[INFO] 
[INFO] --- maven-dependency-plugin:2.5.1:unpack (unpack) @ eswc-2015-frontend ---
[INFO] Configured Artifact: org.ldp4j:ldp4j-config:1.0.0-SNAPSHOT:jar
[INFO] ldp4j-config-1.0.0-SNAPSHOT.jar already unpacked.
[INFO] 
[INFO] --- maven-jgit-buildnumber-plugin:1.2.8:extract-buildnumber (git-buildnumber) @ eswc-2015-frontend ---
[INFO] Git info extracted, revision: 'baafbaa', branch: 'minimalapp', tag: '', commitsCount: '59', buildnumber: 'baafbaa'
[INFO] 
[INFO] --- gmaven-plugin:1.0:execute (buildNumber) @ eswc-2015-frontend ---
Build number: 1.0.0-SNAPSHOT build 59 (minimalapp@baafbaa)
[INFO] 
[INFO] --- jacoco-maven-plugin:0.7.1.201405082137:prepare-agent (default-prepare-agent) @ eswc-2015-frontend ---
[INFO] jacoco.agent.ut.arg set to -javaagent:/home/bakerally/.m2/repository/org/jacoco/org.jacoco.agent/0.7.1.201405082137/org.jacoco.agent-0.7.1.201405082137-runtime.jar=destfile=/home/bakerally/Documents/repositories/github/LDPTest3/frontend/target/coverage-reports/jacoco-ut.exec,includes=org.ldp4j.*
[INFO] 
[INFO] --- build-helper-maven-plugin:1.8:timestamp-property (timestamp-property) @ eswc-2015-frontend ---
[WARNING] Using platform locale (en_US actually) to format date/time, i.e. build is platform dependent!
[INFO] 
[INFO] --- license-maven-plugin:2.6:format (update-licenses) @ eswc-2015-frontend ---
[INFO] Updating license headers...
[INFO] Updating license header in: /home/bakerally/Documents/repositories/github/LDPTest3/frontend/pom.xml
[INFO] Updating license header in: /home/bakerally/Documents/repositories/github/LDPTest3/frontend/core/pom.xml
[INFO] Updating license header in: /home/bakerally/Documents/repositories/github/LDPTest3/frontend/dist/pom.xml
[INFO] 
[INFO] --- build-helper-maven-plugin:1.8:add-resource (install-legal-files) @ eswc-2015-frontend ---
[INFO] 
[INFO] --- build-helper-maven-plugin:1.8:add-resource (install-test-legal-files) @ eswc-2015-frontend ---
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building ESWC 2015 Tutorial :: Frontend :: Core 1.0.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-enforcer-plugin:1.3.1:enforce (enforce-maven-3) @ frontend-core ---
[INFO] 
[INFO] --- maven-dependency-plugin:2.5.1:unpack (unpack) @ frontend-core ---
[INFO] Configured Artifact: org.ldp4j:ldp4j-config:1.0.0-SNAPSHOT:jar
[INFO] ldp4j-config-1.0.0-SNAPSHOT.jar already unpacked.
[INFO] 
[INFO] --- maven-jgit-buildnumber-plugin:1.2.8:extract-buildnumber (git-buildnumber) @ frontend-core ---
[INFO] Git info extracted, revision: 'baafbaa', branch: 'minimalapp', tag: '', commitsCount: '59', buildnumber: 'baafbaa'
[INFO] 
[INFO] --- gmaven-plugin:1.0:execute (buildNumber) @ frontend-core ---
Build number: 1.0.0-SNAPSHOT build 59 (minimalapp@baafbaa)
[INFO] 
[INFO] --- jacoco-maven-plugin:0.7.1.201405082137:prepare-agent (default-prepare-agent) @ frontend-core ---
[INFO] jacoco.agent.ut.arg set to -javaagent:/home/bakerally/.m2/repository/org/jacoco/org.jacoco.agent/0.7.1.201405082137/org.jacoco.agent-0.7.1.201405082137-runtime.jar=destfile=/home/bakerally/Documents/repositories/github/LDPTest3/frontend/core/target/coverage-reports/jacoco-ut.exec,includes=org.ldp4j.*
[INFO] 
[INFO] --- build-helper-maven-plugin:1.8:timestamp-property (timestamp-property) @ frontend-core ---
[WARNING] Using platform locale (en_US actually) to format date/time, i.e. build is platform dependent!
[INFO] 
[INFO] --- license-maven-plugin:2.6:format (update-licenses) @ frontend-core ---
[INFO] Updating license headers...
[INFO] Updating license header in: /home/bakerally/Documents/repositories/github/LDPTest3/frontend/core/pom.xml
[INFO] 
[INFO] --- build-helper-maven-plugin:1.8:add-resource (install-legal-files) @ frontend-core ---
[INFO] 
[INFO] --- build-helper-maven-plugin:1.8:add-resource (install-test-legal-files) @ frontend-core ---
[INFO] 
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ frontend-core ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory /home/bakerally/Documents/repositories/github/LDPTest3/frontend/core/src/main/resources
[INFO] Copying 2 resources
[INFO] Copying 2 resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.1:compile (default-compile) @ frontend-core ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 8 source files to /home/bakerally/Documents/repositories/github/LDPTest3/frontend/core/target/classes
[INFO] -------------------------------------------------------------
[ERROR] COMPILATION ERROR : 
[INFO] -------------------------------------------------------------
[ERROR] /home/bakerally/Documents/repositories/github/LDPTest3/frontend/core/src/main/java/org/ldp4j/tutorial/frontend/parking/ParkingContainerHandler.java:[30,34] cannot find symbol
  symbol:   class DataSetFactory
  location: package org.ldp4j.application.data
[ERROR] /home/bakerally/Documents/repositories/github/LDPTest3/frontend/core/src/main/java/org/ldp4j/tutorial/frontend/parking/ParkingContainerHandler.java:[63,17] cannot find symbol
  symbol:   variable DataSetFactory
  location: class org.ldp4j.tutorial.frontend.parking.ParkingContainerHandler
[ERROR] /home/bakerally/Documents/repositories/github/LDPTest3/frontend/core/src/main/java/org/ldp4j/tutorial/frontend/util/FormatUtil.java:[61,63] cannot find symbol
  symbol:   method formatIndividualId(org.ldp4j.application.data.Individual<capture#1 of ?,capture#2 of ?>)
  location: class org.ldp4j.application.data.FormatUtils
[ERROR] /home/bakerally/Documents/repositories/github/LDPTest3/frontend/core/src/main/java/org/ldp4j/tutorial/frontend/ContactsApplication.java:[105,72] cannot find symbol
  symbol:   method withBase(java.lang.String)
  location: class org.ldp4j.application.data.NamingScheme.NamingSchemeBuilder
[ERROR] /home/bakerally/Documents/repositories/github/LDPTest3/frontend/core/src/main/java/org/ldp4j/tutorial/frontend/ContactsApplication.java:[110,73] cannot find symbol
  symbol:   method withBase(java.lang.String)
  location: class org.ldp4j.application.data.NamingScheme.NamingSchemeBuilder
[INFO] 5 errors 
[INFO] -------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] ESWC 2015 Tutorial ................................. SUCCESS [  3.835 s]
[INFO] ESWC 2015 Tutorial :: Frontend ..................... SUCCESS [  0.120 s]
[INFO] ESWC 2015 Tutorial :: Frontend :: Core ............. FAILURE [  1.123 s]
[INFO] ESWC 2015 Tutorial :: Frontend :: Distributable .... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 5.699 s
[INFO] Finished at: 2017-03-04T00:26:52+01:00
[INFO] Final Memory: 35M/343M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.1:compile (default-compile) on project frontend-core: Compilation failure: Compilation failure:
[ERROR] /home/bakerally/Documents/repositories/github/LDPTest3/frontend/core/src/main/java/org/ldp4j/tutorial/frontend/parking/ParkingContainerHandler.java:[30,34] cannot find symbol
[ERROR] symbol:   class DataSetFactory
[ERROR] location: package org.ldp4j.application.data
[ERROR] /home/bakerally/Documents/repositories/github/LDPTest3/frontend/core/src/main/java/org/ldp4j/tutorial/frontend/parking/ParkingContainerHandler.java:[63,17] cannot find symbol
[ERROR] symbol:   variable DataSetFactory
[ERROR] location: class org.ldp4j.tutorial.frontend.parking.ParkingContainerHandler
[ERROR] /home/bakerally/Documents/repositories/github/LDPTest3/frontend/core/src/main/java/org/ldp4j/tutorial/frontend/util/FormatUtil.java:[61,63] cannot find symbol
[ERROR] symbol:   method formatIndividualId(org.ldp4j.application.data.Individual<capture#1 of ?,capture#2 of ?>)
[ERROR] location: class org.ldp4j.application.data.FormatUtils
[ERROR] /home/bakerally/Documents/repositories/github/LDPTest3/frontend/core/src/main/java/org/ldp4j/tutorial/frontend/ContactsApplication.java:[105,72] cannot find symbol
[ERROR] symbol:   method withBase(java.lang.String)
[ERROR] location: class org.ldp4j.application.data.NamingScheme.NamingSchemeBuilder
[ERROR] /home/bakerally/Documents/repositories/github/LDPTest3/frontend/core/src/main/java/org/ldp4j/tutorial/frontend/ContactsApplication.java:[110,73] cannot find symbol
[ERROR] symbol:   method withBase(java.lang.String)
[ERROR] location: class org.ldp4j.application.data.NamingScheme.NamingSchemeBuilder
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :frontend-core
```

**Comment by mestebangutierrez** [comment]
Humm, it might be the case that the LDP4j Application API has changed a little bit from the version originally used for the [ESWC 2015 tutorial](https://github.com/ldp4j/ldp4j/releases/tag/eswc2015-tutorial) and the latest version ([0.2.1](https://github.com/ldp4j/ldp4j/releases/tag/0.2.1)). I just did the math: 47 classes modified, and 40 more added.

However, I managed to update the ESWC 2015 tutorial to cope with version 0.2.1, just have a look at branch [release/1.0.0](https://github.com/ldp4j/eswc2015-tutorial/tree/release/1.0.0). I hope you don't have to do many changes.

On a side note, I've just realized that I didn't fill in the release notes for the version 0.2.1 :-P

**Comment by noorbakerally** [comment]
yeah notice this ;) in fact, i'm was just trying to make my app work with version 0.2.1, i didn't had to changed much things, so far:

1. DataSetFactory to DataSets
2. DataSetUtils.newTypedLiteral to Literals.newTypedLiterals 

by changing this, it is perfectly compiling, but when running the app, i'm getting an error from guava library,  i'm trying to look into it, will post any updates,

the error is:

```
SLF4J: Failed toString() invocation on an object of type [org.ldp4j.application.kernel.resource.ResourceId]
java.lang.NoClassDefFoundError: com/google/common/base/MoreObjects
	at org.ldp4j.application.kernel.resource.ResourceId.toString(ResourceId.java:89)
	at org.slf4j.helpers.MessageFormatter.safeObjectAppend(MessageFormatter.java:304)
	at org.slf4j.helpers.MessageFormatter.deeplyAppendParameter(MessageFormatter.java:276)
	at org.slf4j.helpers.MessageFormatter.arrayFormat(MessageFormatter.java:230)
	at org.slf4j.helpers.MessageFormatter.format(MessageFormatter.java:152)
	at org.slf4j.impl.Log4jLoggerAdapter.debug(Log4jLoggerAdapter.java:251)
	at org.ldp4j.application.kernel.lifecycle.EnvironmentImpl.configureRootResources(EnvironmentImpl.java:167)
	at org.ldp4j.application.kernel.lifecycle.ApplicationLoader.setup(ApplicationLoader.java:184)
	at org.ldp4j.application.kernel.lifecycle.ApplicationLoader.bootstrap(ApplicationLoader.java:113)
	at org.ldp4j.application.kernel.lifecycle.ApplicationLifecycleService.initialize(ApplicationLifecycleService.java:127)
	at org.ldp4j.application.kernel.engine.DefaultApplicationContext.initialize(DefaultApplicationContext.java:451)
	at org.ldp4j.application.kernel.engine.DefaultApplicationEngine$DefaultApplicationContextManager.createContext(DefaultApplicationEngine.java:181)
	at org.ldp4j.application.kernel.engine.DefaultApplicationEngine$DefaultApplicationContextManager.createContext(DefaultApplicationEngine.java:169)
	at org.ldp4j.application.engine.ApplicationEngine.load(ApplicationEngine.java:273)
	at org.ldp4j.server.setup.BootstrapContextListener.loadApplicationContext(BootstrapContextListener.java:155)
	at org.ldp4j.server.setup.BootstrapContextListener.contextInitialized(BootstrapContextListener.java:106)
	at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:5016)
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5524)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1575)
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1565)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.ClassNotFoundException: com.google.common.base.MoreObjects
	at org.apache.catalina.loader.WebappClassLoader.loadClass(WebappClassLoader.java:1720)
	at org.apache.catalina.loader.WebappClassLoader.loadClass(WebappClassLoader.java:1571)
	... 25 more
SLF4J: Failed toString() invocation on an object of type [org.ldp4j.application.kernel.resource.ResourceId]
java.lang.NoClassDefFoundError: com/google/common/base/MoreObjects
	at org.ldp4j.application.kernel.resource.ResourceId.toString(ResourceId.java:89)
	at org.slf4j.helpers.MessageFormatter.safeObjectAppend(MessageFormatter.java:304)
	at org.slf4j.helpers.MessageFormatter.deeplyAppendParameter(MessageFormatter.java:276)
	at org.slf4j.helpers.MessageFormatter.arrayFormat(MessageFormatter.java:230)
	at org.slf4j.helpers.MessageFormatter.format(MessageFormatter.java:152)
	at org.slf4j.impl.Log4jLoggerAdapter.debug(Log4jLoggerAdapter.java:251)
	at org.ldp4j.application.kernel.lifecycle.EnvironmentImpl.configureRootResources(EnvironmentImpl.java:167)
	at org.ldp4j.application.kernel.lifecycle.ApplicationLoader.setup(ApplicationLoader.java:184)
	at org.ldp4j.application.kernel.lifecycle.ApplicationLoader.bootstrap(ApplicationLoader.java:113)
	at org.ldp4j.application.kernel.lifecycle.ApplicationLifecycleService.initialize(ApplicationLifecycleService.java:127)
	at org.ldp4j.application.kernel.engine.DefaultApplicationContext.initialize(DefaultApplicationContext.java:451)
	at org.ldp4j.application.kernel.engine.DefaultApplicationEngine$DefaultApplicationContextManager.createContext(DefaultApplicationEngine.java:181)
	at org.ldp4j.application.kernel.engine.DefaultApplicationEngine$DefaultApplicationContextManager.createContext(DefaultApplicationEngine.java:169)
	at org.ldp4j.application.engine.ApplicationEngine.load(ApplicationEngine.java:273)
	at org.ldp4j.server.setup.BootstrapContextListener.loadApplicationContext(BootstrapContextListener.java:155)
	at org.ldp4j.server.setup.BootstrapContextListener.contextInitialized(BootstrapContextListener.java:106)
	at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:5016)
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5524)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1575)
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1565)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
Mar 07, 2017 11:24:14 PM org.apache.catalina.core.StandardContext listenerStart
SEVERE: Exception sending context initialized event to listener instance of class org.ldp4j.server.setup.BootstrapContextListener
java.lang.NoClassDefFoundError: com/google/common/base/MoreObjects
	at org.ldp4j.application.kernel.session.WriteSessionConfiguration.toString(WriteSessionConfiguration.java:81)
	at java.util.Formatter$FormatSpecifier.printString(Formatter.java:2838)
	at java.util.Formatter$FormatSpecifier.print(Formatter.java:2718)
	at java.util.Formatter.format(Formatter.java:2488)
	at java.util.Formatter.format(Formatter.java:2423)
	at java.lang.String.format(String.java:2792)
	at org.ldp4j.application.kernel.session.WriteSessionService.logLifecycleMessage(WriteSessionService.java:180)
	at org.ldp4j.application.kernel.session.WriteSessionService.createSession(WriteSessionService.java:118)
	at org.ldp4j.application.kernel.lifecycle.ApplicationLoader.initialize(ApplicationLoader.java:130)
	at org.ldp4j.application.kernel.lifecycle.ApplicationLoader.bootstrap(ApplicationLoader.java:114)
	at org.ldp4j.application.kernel.lifecycle.ApplicationLifecycleService.initialize(ApplicationLifecycleService.java:127)
	at org.ldp4j.application.kernel.engine.DefaultApplicationContext.initialize(DefaultApplicationContext.java:451)
	at org.ldp4j.application.kernel.engine.DefaultApplicationEngine$DefaultApplicationContextManager.createContext(DefaultApplicationEngine.java:181)
	at org.ldp4j.application.kernel.engine.DefaultApplicationEngine$DefaultApplicationContextManager.createContext(DefaultApplicationEngine.java:169)
	at org.ldp4j.application.engine.ApplicationEngine.load(ApplicationEngine.java:273)
	at org.ldp4j.server.setup.BootstrapContextListener.loadApplicationContext(BootstrapContextListener.java:155)
	at org.ldp4j.server.setup.BootstrapContextListener.contextInitialized(BootstrapContextListener.java:106)
	at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:5016)
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5524)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1575)
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1565)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.ClassNotFoundException: com.google.common.base.MoreObjects
	at org.apache.catalina.loader.WebappClassLoader.loadClass(WebappClassLoader.java:1720)
	at org.apache.catalina.loader.WebappClassLoader.loadClass(WebappClassLoader.java:1571)
	... 26 more

Mar 07, 2017 11:24:14 PM org.apache.catalina.core.StandardContext startInternal
SEVERE: Error listenerStart
Mar 07, 2017 11:24:14 PM org.apache.catalina.core.StandardContext startInternal
SEVERE: Context [/contacts] startup failed due to previous errors
Mar 07, 2017 11:24:14 PM org.apache.catalina.core.ApplicationContext log
INFO: Closing Spring root WebApplicationContext
Mar 07, 2017 11:24:14 PM org.apache.catalina.loader.WebappClassLoader checkThreadLocalMapForLeaks
SEVERE: The web application [/contacts] created a ThreadLocal with key of type [java.lang.ThreadLocal] (value [java.lang.ThreadLocal@2cf8548c]) and a value of type [org.ldp4j.application.kernel.session.UnitOfWork] (value [org.ldp4j.application.kernel.session.UnitOfWork@6376ca64]) but failed to remove it when the web application was stopped. Threads are going to be renewed over time to try and avoid a probable memory leak.
Mar 07, 2017 11:24:15 PM org.apache.coyote.AbstractProtocol start
```

**Comment by mestebangutierrez** [comment]
Did you find the problem? Is there anything else I can do to help you solve the issue?
